Luis-Campano/Estacionamiento

index.js

Correción de rama

---

controllers/customerController.js

Controlador (Crud) de customer

Controlador de Customer

---

routes.js

creacion de las rutas para el modulo de customers

creacion de las rutas

---

controllers/customerController.js
index.js
migrations/20220617183735-create-customer.js
models/customer.js
routes.js

**Testeo de las funcionalidade.
Ademas de correción de posibles errores.**

Testing y correciones

---

migrations/20220621223659-create-vehicle.js
models/vehicle.js

Sprint 03 migración de vehículo

---

controllers/vehicleController.js

Se agrego el controlador de las funciones _**CRUD**_ del módulo de vehículo.

Sprint 03 Funciones CRUD

---

controllers/vehicleController.js
models/customer.js
models/vehicle.js

Sprint 03 validaciones y busqueda

Sprint 03 Validaciones y busqueda

---

controllers/vehicleController.js
models/vehicle.js

Sprint 03 test y correcciones de modulo Vehículo

Sprint 3 test y correcciones

---

controllers/typeVehicleController.js

Sprint 04 funciones CRUD, modelo tipo de vehiculo

Sprint 04 funciones CRUD

---

controllers/typeVehicleController.js
controllers/vehicleController.js
models/type.js

Validaciones y función de búsqueda de Tipo de Vehículo

Sprint 04 validaciones y búsqueda del typeVehicle

---

controllers/vehicleController.js
migrations/20220622212539-create-type.js
models/type.js
models/vehicle.js

Sprint 04 relacion entre vehiculo y tipo de vehiculo

Sprint 04 Relacion de vehiculo con tipo de vehiculo

---

routes.js

Sprint 04, Rutas TypeVehicle

---

routes.js

Sprint 04 test y correciones del typeVehicle

---

migrations/20220621223659-create-vehicle.js
migrations/20220622212539-create-type.js
models/type.js
models/vehicle.js

Cambio en las relaciones.
**LISTO....**

Sprint 04, relación

---

controllers/customerController.js
controllers/vehicleController.js
models/vehicle.js
routes.js

Sprint 04, cambios recientes

---

migrations/20220629214919-create-floor.js
migrations/20220629220621-create-rate.js
models/floor.js
models/rate.js

Sprint 05 Migraciones de estacionamiento (planta y tarifa)

Sprint 05 Migraciones de estacionamiento

---

controllers/floorController.js
controllers/rateController.js
routes.js

Controladores de estacionamiento

Sprint 05 controladores de estacionamiento

---

controllers/floorController.js
controllers/rateController.js
controllers/typeVehicleController.js
migrations/20220622212539-create-type.js
models/floor.js
models/rate.js
models/type.js
models/vehicle.js
routes.js

Sprint 05 relaciones de estacionamiento

---

migrations/20220702224705-create-user.js
models/user.js

Sprint 06 Migración de Usuario

---

controllers/userController.js
package-lock.json
package.json

Actividades realizadas.
- Controlador Usuarios
- Instalación dependencia

Sprint 06, Controlador Usuario, Dependencia instala

---

index.js
routes/routes.js
routes/routesNoProtegidas.js

Sprint 06 Rutas de Usuario

---

controllers/Users/sesionController.js
controllers/Users/userController.js
controllers/floorController.js
index.js
middleware/auth.js
migrations/20220702224705-create-user.js
models/user.js
package-lock.json
package.json
routes/routes.js
routes/routesNoProtegidas.js
utils/jwtGenerator.js

Creción del login de usuarios.
Instalación de algunas dependencias.
`npm install`
Para poder instalar las dependencias.
También recuerden agregas el token para la generación de contraseñas.
#Token de contraseña.
`TOKEN_SECRET=`**_toke_de_acceso_**

Sprint 06, Login de usuarios

---

controllers/Users/userController.js
models/user.js
models/vehicle.js

Sprint 06 Validaciones y busqueda de usuarios

Sprint 06 Validaciones y busqueda de usuarios

---

controllers/customerController.js
controllers/rateController.js
controllers/typeVehicleController.js
controllers/vehicleController.js

Correción de los controladores.
Mostrar información anidida

Sprint 06 Correción Controladores

---

controllers/customerController.js
controllers/rateController.js
controllers/registrationController.js
migrations/20220707220356-create-floor.js
migrations/20220707222014-create-registration.js
migrations/20220707222136-create-payment.js
models/floor.js
models/payment.js
models/rate.js
models/registration.js
models/type.js
models/vehicle.js
routes/routes.js

Relacion entre registro y pago

Sprint 06 Relaciones registro-Pago

---

controllers/passwordController.js
package-lock.json
package.json
routes/routesNoProtegidas.js
utils/passwordEmail.js

Sprint 06 Recuperación de contraseña

Sprint 06 Recuperacion de contraseña

---

controllers/passwordController.js
utils/passwordEmail.js

Sprint 06 Correciones y prubas de sprint

Sprint 06 Pruebas y Correciones

---

controllers/paymentController.js
controllers/rateController.js
controllers/registrationController.js
controllers/vehicleController.js
models/registration.js
routes/routes.js

Codificación de controladores.
- Pagos
- Registros

Sprint 07 Controllers

---

routes/routes.js

Sprint 07 Creación de rutas de pago

Sprint 07 Rutas

---

controllers/customerController.js
utils/notificationEmail.js

Notificación al crear un nuevo registro

Sprint 08 - Notificacion de registro del Cliente

---

package-lock.json
package.json
test/index.js

Instalación de dependencias para realizar el test

instalación de dependencias para el Test

---

controllers/customerController.js
models/customer.js
test/customer/add_test.js
test/customer/delete_test.js
test/customer/read_test.js
test/customer/search_test.js
test/customer/update_test.js
test/index.js

Test de Customer

---

controllers/vehicleController.js
models/vehicle.js
test/index.js
test/vehicle/add_test.js
test/vehicle/delete_test.js
test/vehicle/read_test.js
test/vehicle/search_test.js
test/vehicle/update_test.js

Test de Vehiculo

---

controllers/rateController.js
models/rate.js
routes/routes.js
test/index.js
test/rate/add_test.js
test/rate/delete_test.js
test/rate/read_test.js
test/rate/search_test.js
test/rate/update_test.js

Test de Rate

---

controllers/Users/userController.js
controllers/typeVehicleController.js
models/type.js
test/index.js
test/tipoVehiculo/add_test.js
test/tipoVehiculo/delete_test.js
test/tipoVehiculo/read_test.js
test/tipoVehiculo/search_test.js
test/tipoVehiculo/update_test.js
utils/notificationEmail.js

Test de Type Vehicle

---

controllers/floorController.js
models/floor.js
routes/routes.js
test/floor/add_test.js
test/floor/delete_test.js
test/floor/read_test.js
test/floor/search_test.js
test/floor/update_test.js
test/index.js

Test Floor

---

controllers/registrationController.js
models/registration.js
routes/routes.js
test/index.js
test/registration/add_test.js
test/registration/delete_test.js
test/registration/read_test.js
test/registration/search_test.js

Sprin 09, Test registration.
**En este parte del test, se realizo.**
- Creacion de carpeta.
- Archivos .js.
- Cambios en el codigo fuente.

Sprint 09, Test registration

---

config/role.js
controllers/Users/sesionController.js
controllers/Users/userController.js
routes/routes.js
test/index.js
test/users/login_test.js
test/users/read_test.js
test/users/search_test.js
test/users/signup_test.js

**Sprint 09.**
Test de usuarios.
Se realizo.
- creacion de carpeta user.
- documento js.
- cambios en el codigo.

Sprint 09, Test de usuarios

---

controllers/paymentController.js
test/index.js
test/payment/add_test.js
test/payment/read_test.js

**Sprint 09 Test pago.**
Relizado en esta rama.
- creacion de carpeta payment.
- modificacion de codigo.
- prueba

Sprint 09 Test pago

---

models/floor.js
models/registration.js
models/type.js
models/vehicle.js
test/index.js
test/users/login_test.js
test/users/read_test.js
test/users/search_test.js
test/users/signup_test.js

Validaciones en campos ID
